# cuGraph Cheat Sheets sample code

(c) 2020 NVIDIA, Blazing SQL

Distributed under Apache License 2.0

### Imports

In [1]:
import cudf
import cugraph
import json 
import pandas as pd

### Create graph dataframes

We use the Star Wars social network graph prepared by Evelina Gabasova: Gabasova, E. (2016). Star Wars social network. DOI: https://doi.org/10.5281/zenodo.1411479.

In [9]:
interactions = json.loads(open('data/starwars-full-interactions.json', 'r').read())

edges = cudf.from_pandas(pd.DataFrame(interactions['links']))
nodes = cudf.from_pandas(pd.DataFrame(interactions['nodes'])).drop('colour', axis=1).reset_index()

g = cugraph.Graph()
g.from_cudf_edgelist(
    edges
    , source='source'
    , destination='target'
    , renumber=True
)

---

# Graph centrality

---

#### cugraph.centrality.betweenness_centrality.betweenness_centrality()

In [12]:
cugraph.betweenness_centrality(g, k=20, normalized=True, weight=None)

     betweenness_centrality  vertex
0                  0.000000      62
1                  0.000000      69
2                  0.009689      73
3                  0.000000      75
4                  0.000000      77
..                      ...     ...
104                0.059394      92
105                0.000157      22
106                0.001710      85
107                0.000100      88
108                0.000000     107

[109 rows x 2 columns]

#### cugraph.centrality.betweenness_centrality.edge_betweenness_centrality()

In [13]:
cugraph.edge_betweenness_centrality(g, k=20, normalized=True, weight=None)

     src  dst  betweenness_centrality
0      0    1                0.001127
1      0    3                0.003536
2      0    4                0.000798
3      0    8                0.000593
4      0    9                0.000214
..   ...  ...                     ...
393  105  108                0.000000
394  105  109                0.000085
395  107  108                0.000000
396  107  109                0.000085
397  108  109                0.000127

[398 rows x 3 columns]

#### cugraph.centrality.katz_centrality.katz_centrality()

In [14]:
cugraph.katz_centrality(g, alpha=0.05, max_iter=200, tol=1e-07)

     katz_centrality  vertex
0           0.022568      62
1           0.026007      69
2           0.061748      73
3           0.018347      75
4           0.033611      77
..               ...     ...
104         0.067752      92
105         0.033873      22
106         0.085777      85
107         0.042424      88
108         0.028779     107

[109 rows x 2 columns]